### ISSUE TITLE
Feedback for Accordion

### ISSUE THREAD

**Issue by ghost** [KBeltz/07-08-js-mini#2]
https://www.bitballoon.com/sites/cobbler-noel-66264

**Comment by sumeetjain** [comment]
- [x] You might be able to refactor this with `getElementsByClassName` - https://github.com/KBeltz/07-08-js-mini/blob/master/accordion/global.js#L4-L8

**Comment by ghost** [comment]
https://www.bitballoon.com/sites/executor-abuse-88144

**Comment by sumeetjain** [comment]
![purfect](https://cloud.githubusercontent.com/assets/29388/8578921/2e7af72c-2577-11e5-86d8-4245f3ef5109.png)
